f = open("../generated_verilog/mux.v", "w")
f.write("module mux(input a, input b, input sel, output ans);")
f.write("\n")
f.write("\n")
f.write("assign ans = sel ? a : b;")
f.write("\n")
f.write("\n")
f.write("endmodule")
f.close()